import = ["~/.config/alacritty/themes/themes/catppuccin_mocha.toml"]

[window]
opacity = 0.90
decorations = "full"

[font]
size = 12.0

[font.bold]
family = "monospace"
style = "Bold"

[font.bold_italic]
family = "monospace"
style = "Bold Italic"

[font.italic]
family = "monospace"
style = "Italic"

[font.normal]
family = "monospace"
style = "Regular"


